version: 2
jobs:
  build:
    working_directory: ~/docker-airflow
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
         version: 17.05.0-ce

      - run:
         name: list files
         command: ls -lsrt ~/docker-airflow

      - run:
         name: Build Docker image
         command: docker build -t abhioncbr/docker-airflow:$IMAGE_VERSION --build-arg AIRFLOW_VERSION=$AIRFLOW_VERSION -f
          ~/docker-airflow/docker-files/DockerFile .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push abhioncbr/docker-airflow:$AIRFLOW_VERSION

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop