# VERSION 1.0 (apache-airflow)
# AUTHOR: Abhishek Sharma<abhioncbr@yahoo.com>
# DESCRIPTION: apache airflow docker-compose.yml

version: '3'
services:
  airflow:
    image: abhioncbr/docker-airflow:${AIRFLOW_VERSION}
    restart: always
    container_name: airflow-standalone
    environment:
      MODE: standalone
      S3_PATH: ${S3_PATH}
      RBAC_AUTH: ${RBAC_AUTH}
      GCP_PROJECT: ${GCP_PROJECT}
      GCP_USER_NAME: ${GCP_USER_NAME}
    ports:
      - 2222:2222
    volumes:
      - ../airflow/dags:/usr/local/airflow/dags