# VERSION 1.0 (airflow version:1.9.0)
# AUTHOR: Abhishek Sharma
# DESCRIPTION: Docker airflow redis celery container
# BUILD: docker build --rm -t airflow-base:latest DockerFile-Base1.9.0

FROM debian:jessie
MAINTAINER Abhishek Sharma <abhioncbr@yahoo.com>

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

# Airflow
ARG AIRFLOW_VERSION=1.9.0
ENV AIRFLOW_HOME /usr/local/airflow
ENV REDIS_HOME /usr/local/redis
ENV REDIS_DOWNLOAD_URL http://download.redis.io/releases/redis-3.2.5.tar.gz
ENV TORNADO_DOWNLOAD_URL https://files.pythonhosted.org/packages/fa/14/52e2072197dd0e63589e875ebf5984c91a027121262aa08f71a49b958359/tornado-4.5.2.tar.gz
ENV REDIS_DOWNLOAD_SHA1 6f6333db6111badaa74519d743589ac4635eba7a

# Define en_US.
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8
ENV LC_ALL  en_US.UTF-8

RUN set -ex \
    && buildDeps=' \
    	gcc \
		libc6-dev \
		make \
    	wget \
        python-dev \
        libkrb5-dev \
        libsasl2-dev \
        libssl-dev \
        libffi-dev \
        build-essential \
        libblas-dev \
        liblapack-dev \
    ' \
    && echo "deb http://http.debian.net/debian jessie-backports main" >/etc/apt/sources.list.d/backports.list \
    && apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        $buildDeps \
        python-pip \
        vim \
        libmysqlclient-dev \
        apt-utils \
        curl \
        netcat \
        locales \
        sudo \
        libxml2-dev libxslt1-dev python2.7-dev \
    && apt-get install -yqq -t jessie-backports openjdk-8-jre python-requests libpq-dev sshpass openssh-server openssh-client less \
    && sed -i 's/^# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && wget -O redis.tar.gz ${REDIS_DOWNLOAD_URL} \
	&& echo "$REDIS_DOWNLOAD_SHA1 *redis.tar.gz" | sha1sum -c - \
	&& mkdir -p ${REDIS_HOME} \
	&& tar -xzf redis.tar.gz -C ${REDIS_HOME} --strip-components=1 \
	&& rm redis.tar.gz \
	&& make -C ${REDIS_HOME} \
	&& make -C ${REDIS_HOME} install \
	&& pip install pandas \
    && pip install celery \
    && pip install redis \
    && pip install hdfs3

RUN python -m pip install --upgrade pip setuptools wheel \
    && wget -O tornado-4.5.2.tar.gz ${TORNADO_DOWNLOAD_URL} \
    && tar -xzf tornado-4.5.2.tar.gz -C /tmp/ \
    && cd /tmp/tornado-4.5.2 && python /tmp/tornado-4.5.2/setup.py install \
    && cd - && rm tornado-4.5.2.tar.gz && rm -rf /tmp/tornado-4.5.2 \
    && pip install apache-airflow[celery,mysql,hive,hdfs,jdbc,password,async,ldap,slack,redis,s3,gcp_api,druid,devel,devel_hadoop]==$AIRFLOW_VERSION \
    && apt-get remove --purge -yqq $buildDeps libpq-dev \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base

# Set python path so airflow can find pip installed packages.
ENV PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/site-packages/