# VERSION 1.0 (apache-airflow)
# AUTHOR: Abhishek Sharma<abhioncbr@yahoo.com>
# DESCRIPTION: apache airflow docker-compose.yml

version: '3'
services:
  redis:
    image: redis:3.2
    restart: always
    container_name: airflow-task_queue
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    command: --explicit_defaults_for_timestamp=1
    container_name: airflow-metadata_db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  airflow-server:
    image: abhioncbr/docker-airflow:${AIRFLOW_VERSION}
    restart: always
    container_name: airflow-server
    environment:
      MODE: cluster
      NODE_TYPE: server
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      MYSQL_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      S3_PATH: ${S3_PATH}
      RBAC_AUTH: ${RBAC_AUTH}
      GCP_PROJECT: ${GCP_PROJECT}
      GCP_USER_NAME: ${GCP_USER_NAME}
    ports:
      - 2222:2222
    depends_on:
      - mysql
      - redis
    volumes:
      - ../airflow/dags:/usr/local/airflow/dags
  airflow-worker:
    image: abhioncbr/docker-airflow:${AIRFLOW_VERSION}
    restart: always
    container_name: airflow-worker
    environment:
      MODE: cluster
      NODE_TYPE: worker
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      MYSQL_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      S3_PATH: ${S3_PATH}
      RBAC_AUTH: ${RBAC_AUTH}
      GCP_PROJECT: ${GCP_PROJECT}
      GCP_USER_NAME: ${GCP_USER_NAME}
    ports:
      - 5555:5555
    depends_on:
      - mysql
      - redis
    volumes:
      - ../airflow/dags:/usr/local/airflow/dags
volumes:
  mysql:
    external: false
  redis:
    external: false